### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by devopsfactory-in** [adobe/react-native-acpcore#103]
While building  a simple react native app using expo start we are getting the below error, the app works fine without the ACPCore import.

But, when we use the following command to import the dependency, we are getting error
import { ACPCore } from '@adobe/react-native-acpcore';

### Expected Behaviour
App Should run
### Actual Behaviour
Compiler error
|Failed to compile.
|/home/ReactNative/AwesomeProject/node_modules/@adobe/react-native-acpcore/js/models/ACPVisitorID.js 18:12
Module parse failed: Unexpected token (18:12)
|You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 'use strict';
| 
> import type {ACPMobileVisitorAuthenticationState} from './ACPMobileVisitorAuthenticationState';
| 
| class ACPVisitorID
#### Sample Code that illustrates the problem
package.json
-----------
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@adobe/react-native-acpanalytics": "^1.3.0",
    "@adobe/react-native-acpcore": "^1.5.0",
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}
-------------------------------
babel.config.js
-----------------
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};

#### Logs taken while reproducing problem
Failed to compile.
/home/ReactNative/AwesomeProject/node_modules/@adobe/react-native-acpcore/js/models/ACPVisitorID.js 18:12
Module parse failed: Unexpected token (18:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 'use strict';
| 
> import type {ACPMobileVisitorAuthenticationState} from './ACPMobileVisitorAuthenticationState';
| 
| class ACPVisitorID {
}

**Comment by nporter-adbe** [comment]
Hi @devopsfactory-in this is expected. React Native applications built-in Expo do not support [Native Modules](https://reactnative.dev/docs/native-modules-intro) out of the box. This is a limitation of Expo, and one option you have is to eject to ExpoKit. Please see the troubleshooting section of this repo for a little bit more information on Expo.

If you eject to ExpoKit and find this issue persists, please let us know.

Doc: https://docs.expo.io/expokit/eject/?redirected

**Comment by devopsfactory-in** [comment]
Hi @nporter-adbe ,
Thanks for the quick response. I already ejected the app by using 'expo eject'.
The app is working fine until we import the acp core. 
 import { ACPCore } from '@adobe/react-native-acpcore';

**Comment by nporter-adbe** [comment]
@devopsfactory-in I put together a fresh expo app ejected to ExpoKit and I am unable to reproduce your issue. The app runs fine after including the ACPCore import and many other API calls to the SDK.

I am running the app with `npm run ios`.

Repo: https://github.com/nporter-adbe/expo-eject-test

**Comment by devopsfactory-in** [comment]
Hi @nporter-adbe ,
Thanks for the hint. 
It seems like the issue only while we trying the expo command.
We were using 'expo start --web', the issue still exist here. 
We will try npm run ios or android

**Comment by nporter-adbe** [comment]
@devopsfactory-in This is expected. Running an expo app targeted for the web is not supported by our SDKs. Our SDKs are mobile-only and will not function within a web-based environment.

**Comment by devopsfactory-in** [comment]
Hi @nporter-adbe ,
Thanks for the info.
