### ISSUE TITLE
Types declaration / Use with TypeScript

### ISSUE THREAD

**Issue by mpatafio** [adobe/react-native-acpcore#121]
Hello! 

I'm trying to use your React Native libraries in TypeScript files, but no types declaration files have been found. Could you please help me? Does exist a package with @types or have I to define them myself?

Im' using:

"@adobe/react-native-acptarget": "1.3.0",
  "@adobe/react-native-acpcore": "1.5.1",

Thank you in advance.

**Comment by spoorthipujariadobe** [comment]
Hi @mpatafio ,
Could you please add the  declaration files and create a PR? We can help to approve and merge it.

**Comment by andrewdami11** [comment]
Yep, I resonate with that. It would be nice to have Typescript functionality

**Comment by spoorthipujariadobe** [comment]
We do not plan to add Typescript support to the ACP React Native SDKs. Please feel free to check out our new AEP React Native SDK mono repo (link to mono repo) which has Typescript support. We are working to extend the mono repo to include more extension in the coming days.
