### ISSUE TITLE
 Issue with the ACPCore npm module for React Native

### ISSUE THREAD

**Issue by jobauman** [adobe/react-native-acpcore#131]
### Expected Behaviour
Working In documentation and in code execution:
<img width="335" alt="Screen Shot 2022-08-09 at 10 59 40 AM" src="https://user-images.githubusercontent.com/110934869/183742834-719da03c-7c2c-44bf-b7a2-9dddb6b3f144.png">

### Actual Behaviour
Broken in git: 
<img width="313" alt="Screen Shot 2022-08-09 at 10 59 24 AM" src="https://user-images.githubusercontent.com/110934869/183742771-676a44e9-6d07-432f-8118-00a6b7fcd80e.png">

**Comment by yangyansong-adbe** [comment]
@jobauman thank you for reporting this! But I don't understand where the issue is, can you give more information on details?

**Comment by jobauman** [comment]
There is an issue with the the ACPCore npm module for React Native, outlined above

**Comment by cacheung** [comment]
@jobauman Which file you are referring to? How it is broken? You are not able to build the app?
Do you mean
#import <React/RCTBridgeModule.h> is broken or not correct?

**Comment by jobauman** [comment]
The github shows #import <react/rctBridgeModule.h> 

but it should be #import "react/rctBridgeModule.h" with the quotes instead. That is what works in code execution and what the documentation says

**Comment by cacheung** [comment]
Hi @jobauman do you refer to 
https://github.com/adobe/react-native-acpcore/blob/main/ios/src/Core/RCTACPCore.h#L14
Or when importing them in the native client app?
And referring to .h file or .m file?

**Comment by jobauman** [comment]
Yes, that's it
We called out the issue in the .h file, may want to check the .m file too?

**Comment by yangyansong-adbe** [comment]
Objective-C supports both `<>` and `""` forms for importing header files, just like C/C++. For the difference see: https://stackoverflow.com/questions/1044360/import-using-angle-brackets-and-quote-marks

Btw, this React Native library was created by following the official documentation: https://reactnative.dev/docs/native-modules-setup, as the documentation said, if you run `npx create-react-native-library react-native-awesome-module` locally, you will see the use of `#import <React/RCTBridgeModule.h>` in the header files. 

So, I don't think it's an issue. Let me close this issue.
