### ISSUE TITLE
Does Adobe provide Crash Analytics for the mobile app developed using React Native / Native Code

### ISSUE THREAD

**Issue by samir-mirani-tcs** [adobe/react-native-acpcore#132]
Hi there!

Just wanted to know whether Adobe provide Crash Analytics for the mobile app developed using React Native / Native Code or not?

**Comment by cacheung** [comment]
@samir-mirani-tcs You can get the Adobe Analytics crash metric with Mobile SDK[ Lifecycle](https://github.com/adobe/react-native-acpcore#lifecycle). It is recommended to implement it in the native code level. 

Please refer to the implementation doc [here](https://aep-sdks.gitbook.io/docs/foundation-extensions/mobile-core/lifecycle)

**Comment by praschetan** [comment]
@samir-mirani-tcs - to clarify, Adobe does not provide crash or performance analytics beyond the metric @cacheung indicates.
