### ISSUE TITLE
Build failed: Could not resolve com.adobe.marketing.mobile:sdk-core:1.+.

### ISSUE THREAD

**Issue by expouic** [adobe/react-native-acpcore#134]
### Expected Behaviour
Build success
### Actual Behaviour
FAILURE: Build failed with an exception.

 * What went wrong:
 Could not determine the dependencies of task ':app:processInhouseResources'.
 > Could not resolve all task dependencies for configuration ':app:InhouseRuntimeClasspath'.
    > Could not resolve com.adobe.marketing.mobile:sdk-core:1.+.
      Required by:
          project :app
          project :app > project :adobe_react-native-acpcore
          > Failed to list versions for com.adobe.marketing.mobile:sdk-core.
          > Unable to load Maven meta-data from https://www.jitpack.io/com/adobe/marketing/mobile/sdk-core/maven-metadata.xml.
          > Could not GET 'https://www.jitpack.io/com/adobe/marketing/mobile/sdk-core/maven-metadata.xml'. Received status code 521 from server: 

 * Try:
 > Run with --stacktrace option to get the stack trace.
 > Run with --debug option to get more log output.
 > Run with --scan to get full insights.
 
 * Get more help at https://help.gradle.org/
 
BUILD FAILED in 6m 15s

#### Platform and Version
package.json
 ```"dependencies": {
    "@adobe/react-native-acpcampaign": "2.0.1",
    "@adobe/react-native-acpcore": "2.0.2", 
    ....
}```

**Comment by cacheung** [comment]
Hi @expouic,
     I saw there was a recent react-native issue.
     Can you add the below lines in build.grade under allprojects and see if the issue is resolved?
     
    allprojects {
    repositories {
 
        exclusiveContent {
        filter {
          includeGroup "com.facebook.react"
        }
        forRepository {
          maven {
            url "$rootDir/../node_modules/react-native/android"
          }
        }
      }
    }
}

Thanks,
Calise

**Comment by expouic** [comment]
I think the issue is related to [this](https://github.com/jitpack/jitpack.io/issues/5337) one. I tried your suggestion but still got the same error: 
```Failed to get resource: GET. [HTTP HTTP/1.1 521 : https://www.jitpack.io/com/adobe/marketing/mobile/sdk-core/maven-metadata.xml)]```

**Comment by expouic** [comment]
Now the [jitpack.io](https://www.jitpack.io/com/adobe/marketing/mobile/sdk-core/maven-metadata.xml) returns Repository not found: https://marketing.adobe.com/mobile/sdk-core

**Comment by cacheung** [comment]
It is good to know. It seems like the jitpack is up just now from the thread you provided. Can you try again?

Thanks,
Calise

**Comment by cacheung** [comment]
I am not seeing the same error in our sample app now.  If you still see that, try to delete node_modules and rerun npm install.

**Comment by expouic** [comment]
It's working now. After Jitpack Server became available again.
