### ISSUE TITLE
Make this wrapper cocoapod compatible

### ISSUE THREAD

**Issue by booker-dragon** [adobe/react-native-acpcore#2]
In  the installation section, we have to manually link all needed libraries.

I think we can make this compatible with Cocoapod and include all needed libraries in the podspec

**Comment by nporter-adbe** [comment]
@booker-dragon thanks for the suggestion! I think this could make the installation process a bit easier on the iOS side. We'll take a look into this.

**Comment by booker-dragon** [comment]
I have created a PR for this but I am not an expert of iOS development
I am not sure if I am doing it in the right way but it works

**Comment by booker-dragon** [comment]
This is not going to be addressed?
