### ISSUE TITLE
RN0.60.x autolink support

### ISSUE THREAD

**Issue by booker-dragon** [adobe/react-native-acpcore#31]
## Expected Behaviour
After `npm i --save @adobe/react-native-acpcore`, the project should be automatically linked to the project without running `react-native link`

### Actual Behaviour
It is not compatible with RN0.60.x

#### Platform and Version
iOS  & Android

https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#autolinking
According to this documentation, iOS project requires to have a podspec to work with new autolink.

Please update the README for RN 0.60x installation steps

**Comment by nporter-adbe** [comment]
Hi, 
Just to clarify, does the package not work with RN0.60.x projects or does it not take advantage of the auto linking capability to simplify installation?

**Comment by booker-dragon** [comment]
I cannot link the project properly (auto / manual), so I cannot build the
app to test it

**Comment by booker-dragon** [comment]
I finally build the app successfully with the sdk

I have to manually remove the `libRCTACPCore.a` and re-add it manually to correctly link the library

I think #26 should be merging ASAP as it should solve the issue easily

**Comment by nporter-adbe** [comment]
@booker-dragon I've made PR's into Core and Analytics with changes required for 0.60.0 support. I'll be out on PTO next week and won't have time to release these changes on npm. But in the meantime you can try out these changes with something like:

```
npm install https://github.com/adobe/react-native-acpcore\#RN6-podspec --save
npm install https://github.com/adobe/react-native-acpanalytics\#RN6-podspec --save
```
Can you try out these and let me know if they resolve your issue? From my testing these run with no issue on 0.60.x.

**Comment by booker-dragon** [comment]
Great, I have tried to add podspec myself, Xcide build is working but react
native cli failed

I will try your branch and feedback soon

**Comment by booker-dragon** [comment]
I tested, seems core and analytics work fine

**Comment by booker-dragon** [comment]
Tested, iOS failed to link the project automactically

**Comment by booker-dragon** [comment]
Sorry, I forgot to reply
The sdk is fine but with react native run-ios
It throws error for duplicate symbols

**Comment by nporter-adbe** [comment]
@booker-dragon This is an error on your side most likely caused by attempting to link the SDK multiple times.

I have been able to install the SDK and run them with no issue in multiple 0.60.x apps.

Here is the log output when I run `react-native run-ios` in a fresh 0.60.x app.
https://gist.github.com/nporter-adbe/46422c3b75844088adb995439c95c3ff

**Comment by booker-dragon** [comment]
> @booker-dragon This is an error on your side, most likely caused by attempting to link the SDK multiple times.
> 
> I have been able to install the SDK and run them with no issue in multiple 0.60.x apps.
> 
> Here is the log output when I run `react-native run-ios` in a fresh 0.60.x app.
> https://gist.github.com/nporter-adbe/46422c3b75844088adb995439c95c3ff

I fixed the issue, I need to manually remove ios/build folder to remove duplicate symbols
