### ISSUE TITLE
Is ACPCore using UIWebview on iOS?

### ISSUE THREAD

**Issue by booker-dragon** [adobe/react-native-acpcore#48]
Hi team,

I am submitting my app to Apple AppStore and I am getting warning of UIWebView usage.

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I run `grep -r UIWebView node_modules/` and found that UIWebView is found in `node_modules/@adobe/react-native-acpcore/ios/libs/libACPCore_iOS.a`

Please advise.

Thanks!

**Comment by nporter-adbe** [comment]
Hi @booker-dragon, what version of `react-native-acpcore` are you using? We fixed this issue in `v1.1.2`.
