### ISSUE TITLE
ACPCore.h not found when importing <RCTACPCore/ACPCore.h>

### ISSUE THREAD

**Issue by BoilingOil** [adobe/react-native-acpcore#50]
### Expected Behaviour

ACPCore should be found.

### Actual Behaviour

ACPCore is not found.

### Reproduce Scenario (including but not limited to)

npm i @adobe/react-native-acpcore

react-native link @adobe/react-native-acpcore

#### Steps to Reproduce

npm i @adobe/react-native-acpcore

react-native link @adobe/react-native-acpcore

press play in xcode

#### Platform and Version

MacOS 10.14.6

Xcode 11.1

React Native 0.59.9

#### Sample Code that illustrates the problem

#import <RCTACPCore/ACPCore.h>

**Comment by nporter-adbe** [comment]
Hi @BoilingOil, any chance you're using cocoapods? If you may need to `pod install` in your iOS directory.

**Comment by nporter-adbe** [comment]
@BoilingOil I wasn't able to reproduce this issue on RN `0.59.9` following the steps provided. I tested this in Xcode 10.2 and the latest version of Xcode. 
Here is that app: https://github.com/nporter-adbe/gitissue50

**Comment by BoilingOil** [comment]
I'm not using cocoapods.

What I've tried:

Cleaning the build folder: This will remove the error from AppDelegate, but upon pressing build and run, the build will fail and the error returns.

I've unlinked 1.1.1, uninstalled 1.1.1, installed 1.1.2, and linked 1.1.2.

I continue to have the error.

What I believe to be strange: I am able to jump to definition and land on ACPCore.h

**Comment by nporter-adbe** [comment]
@BoilingOil  Sounds like when react native linked the library it didn't update your header search paths? Make sure you have a recursive header search path of `$(SRCROOT)/../node_modules/@adobe/react-native-acpcore/ios/src` 

You can see an example of this in the app I linked above, even though I didn't need to manually add the header search path.

**Comment by BoilingOil** [comment]
I have that entry in header search paths. I will compare the gitissue50 project to my own and see what's changed.

**Comment by BoilingOil** [comment]
Closing this.

**Comment by Anujmoglix** [comment]
#import "ACPCore.h" and added recursive header search path of $(SRCROOT)/../node_modules/@adobe/react-native-acpcore/ios/src

but still getting issue.
