### ISSUE TITLE
pod install errors

### ISSUE THREAD

**Issue by activebiz** [adobe/react-native-acpcore#57]
### Expected Behaviour

when doing pod install (after npm install) it should update cocapod list. 

### Actual Behaviour

pod install gives following error.

```
pod install
Detected React Native module pods for RCTACPCore, RNCMaskedView, RNGestureHandler, RNKeychain, RNReanimated, RNScreens, RNVectorIcons, ReactNativeExceptionHandler, react-native-safe-area-context, and react-native-webview
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "RCTACPCore":
  In Podfile:
    RCTACPCore (from `../node_modules/@adobe/react-native-acpcore`)

Specs satisfying the `RCTACPCore (from `../node_modules/@adobe/react-native-acpcore`)` dependency were found, but they required a higher minimum deployment target.
```

### Reproduce Scenario (including but not limited to)
Adding to existing React > 0.60 project
#### Steps to Reproduce
```
npm install --save-exact @adobe/react-native-acpcore
cd ios 
pod install
```

#### Platform and Version
    "react": "16.9.0",
    "react-native": "0.61.5",

**Comment by nporter-adbe** [comment]
Hi, the AEP SDK’s have a minimum iOS version of 10.0. It sounds like your podfile is specifying a version lower than 10.0 which is causing this error. 

https://github.com/adobe/react-native-acpcore/blob/master/ios/Podfile#L1

**Comment by activebiz** [comment]
I got xcode 11.3 installed.

**Comment by activebiz** [comment]
Thanks there seems to be number of ways to do this. What is the best way to fix verison number?

**Comment by nporter-adbe** [comment]
You need to update the iOS version in your podfile, e.g.: https://github.com/adobe/react-native-acpcore/blob/master/ios/Podfile#L1

**Comment by nporter-adbe** [comment]
@activebiz Did this solve your issue?

**Comment by activebiz** [comment]
Yes it has thank you.
