### ISSUE TITLE
Initialization in JS

### ISSUE THREAD

**Issue by Olgagr** [adobe/react-native-acpcore#88]
### Expected Behaviour
According to documentation on Adobe site for React Native (https://aep-sdks.gitbook.io/docs/getting-started/get-the-sdk#2-add-initialization-code), I can register and start ACPCore from JavaScript like this

```

async componentWillMount(){
        await this.initSDK();
    }

async initSDK() {
    ACPCore.setLogLevel(ACPMobileLogLevel.VERBOSE);
    ACPCore.configureWithAppId("some_id");
    ACPLifecycle.registerExtension();
    ACPIdentity.registerExtension();
    ACPSignal.registerExtension();
    await ACPCore.start();
}
```

### Actual Behaviour
When I try to initialize like that I get these errors:

```
Registering Lifecycle extension failed with error: null
Registering Identity extension failed with error: null
Registering Signal extension failed with error: null
```

#### Logs taken while reproducing the problem
```
Registering Lifecycle extension failed with error: null
Registering Identity extension failed with error: null
Registering Signal extension failed with error: null
```

In the README there is nothing about such initialization. Is it still supported?

**Comment by imironchuk** [comment]
Hi @Olgagr  - we recommend that you initialize the Core modules for the SDK in your native projects: https://aep-sdks.gitbook.io/docs/getting-started/get-the-sdk#javascript

**Comment by Olgagr** [comment]
@imironchuk Yes, I saw this documentation and there is a snipped for React Native:

![Screenshot 2020-11-09 at 17 47 30](https://user-images.githubusercontent.com/1297219/98570711-0481b880-22b4-11eb-9cb6-3e376a85f65a.png)

Is it obsolete? As it suggests that the initialization can be done like that as well.

**Comment by nporter-adbe** [comment]
@Olgagr The code snippet you linked does suggest that you can in-fact initialize the SDK within Javascript, but the note above suggests to use native code instead, for a few reasons.

1. It is highly likely that in future versions we will deprecate the ability to register extensions and start the SDK in Javascript.
2. Initializing in Javascript can lead to undesirable behavior, and have often had negative impacts on Lifecycle metrics.

If you are newly implementing the SDK via React Native initializing the SDK should be done with native code.

**Comment by Olgagr** [comment]
@nporter-adbe Thanks for the explanation. That is precious knowledge. What about adding this information to the README file? People that are coming from JS word would usually want to operate on the JS side. If they see that they can make initialization in the preferred environment and there are no reasoning behind not doing so, they will probably go with JS.

**Comment by nporter-adbe** [comment]
@Olgagr, thanks for the feedback. We currently note in the README that initialization should be done in native code; however, it doesn't include an explanation about why it is required/recommended. Maybe we should consider removing the sample JS code.

https://github.com/adobe/react-native-acpcore#initializing

**Comment by Olgagr** [comment]
@nporter-adbe Yes, it would be super helpful if there is some more explanation why we should use native code for the initialization. Thank you!
