### ISSUE TITLE
Question: is there any version of this wrapper that supports iOS 9?

### ISSUE THREAD

**Issue by Olgagr** [adobe/react-native-acpcore#95]
Is there any version of this wrapper that can be used on iOS 9? I know that version 4 SDK will not be supported soon but our application needs to support iOS 9.

**Comment by nporter-adbe** [comment]
Hi, the minimum supported iOS version for the V5 SDK is iOS 10.0, therefore the wrappers also have a minimum SDK version of iOS 10.0.

**Comment by Olgagr** [comment]
@nporter-adbe Ok, thank you. We managed to implement the solution that still allows to use this wrapper, even if the target platform is iOS 9. I think it might be useful for others that struggle with the same issue. Do you think it is worth documenting this, e.g. in the README file or should I rather add a comment with the description?

**Comment by nporter-adbe** [comment]
It's currently documented in the README and in the official docs several times. 

> The AEP SDK's require at least iOS 10.0 to function properly. If you see this error, ensure your Podfile specfies at least iOS 10.0.

https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep#upgrade-checklist

https://aep-sdks.gitbook.io/docs/resources/frequently-asked-questions#what-os-and-platform-versions-are-supported

**Comment by Olgagr** [comment]
@nporter-adbe I think I wasn't clear enough. I understand that SDK requires at least iOS 10 but we managed to install it (of course not use it) on device with iOS 9. Our requirements is that for iOS 10 and above, SDK is available but below is not. However, you need to install SDK also for iOS 9 which gives you an error. We found the solution for that which might be useful for others.

**Comment by imironchuk** [comment]
Hi @Olgagr  - Good to see that you were able to get this to work with iOS 9. As @nporter-adbe mentioned we do not have any official support for iOS 9 with the latest SDKs, and while there may be workarounds, we would not wish to promote this. Thanks!
